### ISSUE TITLE
convert.o problem during compilation

### ISSUE THREAD

**Issue by Initiale** [Arksine/Easycam#8]
![untitled](https://cloud.githubusercontent.com/assets/7656871/15181083/d4362638-178d-11e6-855a-0bc7d5af3e44.png)

i solved previous librs problem by download it from ndk site, but compile stuck in something like above... anyone can help ?

**Comment by Arksine** [comment]
If you downloaded libRSsupport.so and placed it in the ndk, then I assume you are using NDK 11.  NDK  11 left out support for renderscript, thus the NDK cannot find llvm-rs-cc.exe, which is needed to compile the renderscript kernel.  You need NDK r10e.  You need to change the compatibility mode for llvm-rs.cc.exe to Windows 7.

This is a copy of issue #2,which I will leave open until google fixes the various renderscript issues.

**Comment by Initiale** [comment]
problem solved... thank you...
